<div class="content">
    <div class="container">
        <div class="row">
            <?php if ($this->tegList === (array)$this->tegList && count($this->tegList) > 0) : ?>
            <div class="col-md-12">
                <div class="tags_block">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <?php foreach ($this->tegList as $url => $name) : ?>
                                    <a style="margin-top:10px;" class="<?= ($name['teg_name'] == $this->currentTeg) ? 'active-teg' : '';?>" href='/teg/<?= $name['teg_name']; ?>/'><?= $name['teg']; ?></a>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php endif; ?>
            <div class="col-md-12">
                <div class="breadcrumbs">
                    <ul>
                        <li><a href="<?= $this->baseUrl() ?>/">Главная</a></li>
                        <li><a href="<?= $this->baseUrl() ?>/<?php echo($this->razdelUrl); ?>/"><?php echo($this->name); ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>     
    <div class="blog" id="razdel-page-main">
        <?php if (count($this->text)>0) : ?>
        <?php $n = 0; ?>
        <div class="container">
        <h1><?php echo(trim($this->name)); ?></h1>
        </div>
        <?php foreach ($this->text as $k => $v): ?>
        <?php 
            $text = $v['m1'];
            //var_dump($v);
            $pos = strpos($text, '$END$');
            $cutText = substr($text, 0, $pos);
            //var_dump($pos);
        ?>
            <div class="blog_article">    
                <div class="container">
                    <div class="row">
                        <?php if ($n % 2 == 0) : ?>
                            <div class="col-sm-6 prev_img">                 
                                <a href="<?= $this->baseUrl() ?>/<?php echo($v['url']); ?>/<?php echo($v['m4_urlname']); ?>/">
                                    <img src="<?= $this->baseUrl() ?>/public/image/statyi/<?php echo($v['m0']); ?>" alt="<?php echo($v['m4']); ?>">
                                </a>
                            </div>
                            <div class="col-sm-6 text">
                                <a class="clean-a" 
                                   href="<?= $this->baseUrl() ?>/<?php echo($v['url']); ?>/<?php echo($v['m4_urlname']); ?>/"
                                   title="<?php echo($v['m4']); ?>"
                                   >
                                    <h2><?php echo($v['m4']); ?></h2>
                                </a>
                                <?php echo $cutText; ?>
                                <div class="readmore">
                                    <a href="<?= $this->baseUrl() ?>/<?php echo($v['url']); ?>/<?php echo($v['m4_urlname']); ?>/">Подробнее</a>
                                </div>                                     
                            </div>
                        <?php else: ?>
                            <div class="col-sm-6 col-sm-push-6 prev_img">                 
                                <a href="<?= $this->baseUrl() ?>/<?php echo($v['url']); ?>/<?php echo($v['m4_urlname']); ?>/">
                                    <img src="<?= $this->baseUrl() ?>/public/image/statyi/<?php echo($v['m0']); ?>" alt="<?php echo($v['m4']); ?>">
                                </a>
                            </div>
                            <div class="col-sm-6 col-sm-pull-6 text">
                                <a class="clean-a" 
                                   href="<?= $this->baseUrl() ?>/<?php echo($v['url']); ?>/<?php echo($v['m4_urlname']); ?>/"
                                   title="<?php echo($v['m4']); ?>" 
                                   >
                                    <h2><?php echo($v['m4']); ?></h2>
                                </a>
                                <?php echo $cutText; ?>
                                <div class="readmore">
                                    <a href="<?= $this->baseUrl() ?>/<?php echo($v['url']); ?>/<?php echo($v['m4_urlname']); ?>/">Подробнее</a>
                                </div>                                     
                            </div>
                           
                        <?php endif; ?>
                        <?php $n++; ?>
                    </div>
                </div>
            </div> 
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
    <div class="container new_art" id="main_page_search_block" style="display:none;">
        
    </div>

    <div class="tags_block">
        <div class="container">
            <div class="row">
<!--    TEGS add later        <div class="col-md-12">
                    <a href="#">Tag link</a>
                    <a href="#">Tag link</a>
                    <a href="#">Tag link</a>
                    <a href="#">Tag link</a>
                    <a href="#">Tag link</a>
                    <a href="#">Tag link</a>
                    <a href="#">Tag link</a>
                    <a href="#">Tag link</a>
                </div>-->
            </div>
        </div>
    </div>
</div>