<?php if(count($this->postsbyteg)>0):?>
<?php //var_dump($this->postsbyteg);?>
<div class='main head'>
    <div class='razdel-name'>
        <h2><i>Вы в разделе "<b><span id="razdel-name-to"></span></b>"</i></h2>
    </div>
    <?php foreach($this->postsbyteg as $k=>$v):?>
       
            <div class="row">
                  
                <div class="post-content">
                    <div class="post-img">
                        <a class="razdel-links" href="<?=$this->baseUrl()?>/post-<?php echo($v['id']);?>/">
                            <img src="<?=$this->baseUrl()?>/image/statyi/<?php echo($v['m0']);?>"/>
                        </a>    
                    </div>
                    <div class="public-date">
                        <p>Статья опубликована: <?php echo(date("Y-m-d",$v['m3']));?></p>
                    </div>
                    <div class="post-h1">
                        <h2>
                            <a class="tega" href="<?=$this->baseUrl()?>/post-<?php echo($v['id']);?>/">
                                <?php echo($v['m4']);?>
                            </a>
                        </h2>
                    </div> 
                    <div class="post-text">
                        <?php $post = mb_substr($v['m1'], 0 , 300 , 'utf8')."...";?>
                        <span><?php echo($post);?></span>
                   </div>
                    
                    <div class="post-next">
                        <a class="tega"  href="<?=$this->baseUrl()?>/post-<?php echo($v['id']);?>/">Читать...</a> 
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        
    <?php endforeach;?>
</div>
<?php else:?>
    <div>По выбранному тегу статей пока нет.</div>
<?php endif;?>

    
    
    
    
    
 