
<div>
<form id="post-form" enctype="application/x-www-form-urlencoded" method="post" action="">
    <div class="an-main">
        <div class="an-m">
            <span>Выберите раздел</span>
            <select name="razdels_info" id="razdels_info">
            <?php foreach($this->razdels_mas as $k=>$v):?>
                    <option value="<?php echo($k);?>" label="<?php echo($v);?>"><?php echo($v);?></option>
            <?php endforeach;?>
            </select>
        </div>
        <div class="an-m">
            <span>Укажите название фотки для превью статьи</span>
            <input type="text" value="" name="img_name" id="img_name">
        </div>    
        <div class="an-m">
            <span>Название статьи</span>
            <input id="h1_post" class="inputs-w100" type="text" name="h1_post" value="">
        </div>
        <div class="an-m">
            <span>Текст статьи</span>
            <textarea  id="body_post" class="inputs-w100 tx-ar" name="body_post"></textarea>
        </div>
        <div class="an-m">
            <span>Теги статьи</span>
            <input id="teg_post" class="inputs-w100" type="text" name="teg_post" value="">
        </div>
        <div class="an-m">
            <span>Description</span>
            <input id="desc" class="inputs-w100" type="text" name="desc" value="">
        </div>
        <div class="an-m">
            <span>Keywords</span>
            <input id="keys" class="inputs-w100" type="text" name="keys" value="">
        </div>
        <div class="an-m button" id="save_post">Сохранить и разместить</div>
    </div>
</form>
</div>

<style>
   .inputs-w100
   {
       width:100%;
       padding:5px;
   }
   .an-m
   {
       margin:10px;
       padding:10px;
   }
   .tx-ar
   {
       min-height:300px;
       resize:none;
   }
   .button
   {
       width:140px;
       height:15px;
       margin:20px;
       padding:10px;
       border:1px dashed green;
   }
   #save_post:hover
   {
       cursor:pointer;
   }
</style>
<script type="text/javascript">
    $(document).ready(function(){
        var flag = 1;
        $
        
        $('#save_post').click(function(){
            var erors = 0;
            
              
            if($.trim($('#img_name').val()) == "")
            {
                $('#img_name').animate({ backgroundColor: "#FFD3D3" }, "slow");
                $('#img_name').animate({ backgroundColor: "#fff" }, "slow");
                
                var  erors = 1;
            }
            
            if($.trim($('#h1_post').val()) == "")
            {
                $('#h1_post').animate({ backgroundColor: "#FFD3D3" }, "slow");
                $('#h1_post').animate({ backgroundColor: "#fff" }, "slow");
                
                var  erors = 1;
            }
            
            if($.trim($('#body_post').val()) == "")
            {
                $('#body_post').animate({ backgroundColor: "#FFD3D3" }, "slow");
                $('#body_post').animate({ backgroundColor: "#fff" }, "slow");
                
                var  erors = 1;
            }
            
            if($.trim($('#teg_post').val()) == "")
            {
                $('#teg_post').animate({ backgroundColor: "#FFD3D3" }, "slow");
                $('#teg_post').animate({ backgroundColor: "#fff" }, "slow");
                
                var  erors = 1;
            }
            
            if($.trim($('#desc').val()) == "")
            {
                $('#desc').animate({ backgroundColor: "#FFD3D3" }, "slow");
                $('#desc').animate({ backgroundColor: "#fff" }, "slow");
                
                var  erors = 1;
            }
            
            if($.trim($('#keys').val()) == "")
            {
                $('#keys').animate({ backgroundColor: "#FFD3D3" }, "slow");
                $('#keys').animate({ backgroundColor: "#fff" }, "slow");
                
                var  erors = 1;
            }
            
            if(flag == 1 && erors == 0)
            {
                flag = 1;
                $.post('/jenstvenayamoda.ru/savepost',$('#post-form').serialize(),function(result){
                    if(result.status == 1)
                    {
                        location.href = '/jenstvenayamoda.ru/'+result.razdel+'/'+result.post;
                        
                    }
                    flag = 1;
                },'json');
            }
            
            
        });
    });
</script>