<div class="slider hidden-xs " id="slider1_container" style="z-index:-1; position: relative; top: -60px; left: 0px; width: 1920px; height: 1024px;">
    <!-- Slides Container -->
    <div u="slides" style="cursor: move; position: absolute; overflow: hidden; left: 0px; top: 0px; width: 1920px; height: 700px;">
        <div><img u="image" alt="Женственный стиль" src="/public/image/mainbanner/1.jpg" /></div>
        <div><img u="image" alt="Модные цвета" src="/public/image/mainbanner/2.jpg" /></div>
        <div><img u="image" alt="С чем носить" src="/public/image/mainbanner/3.jpg" /></div>
        <div><img u="image" alt="Вечерняя мода" src="/public/image/mainbanner/4.jpg" /></div>
        <div><img u="image" alt="Вечерняя мода" src="/public/image/mainbanner/5.jpg" /></div>
        <div><img u="image" alt="Вечерняя мода" src="/public/image/mainbanner/6.jpg" /></div>
        <div><img u="image" alt="Вечерняя мода" src="/public/image/mainbanner/7.jpg" /></div>
        <!--        <div><img u="image" alt="Свадебная мода" src="/public/image/mainbanner/12.jpg" /></div>-->
    </div>
</div>


