<?= $this->partial('index/gallery.phtml'); ?>

<div class="content">
    <div class="container article_block">
        <div class="row">
            <div class="col-md-12">
                <h1>Лучший сайт о моде</h1>
                <p>Каждая женщина  - это особый и неповторимый образ, подобный изысканному бриллианту. Любому драгоценному камню нужна соответствующая оправа. Женственная одежда, украшения, аксессуары – это ваши помощники в деле самовыражения и выбора собственного стиля.
                    Кто вы? Легкомысленная кокетка, изысканная леди, очаровательная романтичная барышня или озорная непосредственная девчонка? Откройте себя заново с сайтом Женственная мода.</p>

            </div>
        </div>
    </div>
    <div class="container new_art" id="main_page_block">
        <h2>Новые статьи</h2>
        <?php
        $i = 0;
        $effectsArray = array(
            0 => 'slideInLeft',
            1 => 'slideInRight',
            2 => 'zoomIn'
        );
        ?>
        <?php foreach ($this->postsBlock1 as $key => $value) : ?>
            <?php if ($i == 0) : ?>
                <div class="row">
                <?php endif; ?>    
                <div class="col-sm-6 col-md-6">
                    <div class="new_art_block wow <?php echo $effectsArray[$i]; ?>">
                        <div class="new_art_img">
                            <a href="<?php echo $this->baseUrl(); ?>/<?php echo($value['razdel_url']); ?>/<?php echo($value['href']); ?>/">
                                <img src="public/image/statyi/<?php echo $value['img']; ?>" alt="<?php echo $value['name']; ?>">
                            </a>
                            <div class="new_art_lbl"><?php echo $value['razdel']; ?></div>
                        </div>
                        <div class="new_art_title">
                            <a href="<?php echo $this->baseUrl(); ?>/<?php echo($value['razdel_url']); ?>/<?php echo($value['href']); ?>/">
                                <?php echo $value['name']; ?>
                            </a>
                        </div>
                        <div class="new_art_date"><?php echo date("Y.m.d", $value['time']); ?></div>
                    </div>
                </div>
                <?php if ($i == 1) : ?>
                </div>
            <?php endif; ?>
            <?php
            if ($i == 1) {
                $i = 0;
            } else {
                $i++;
            }
            ?>

        <?php endforeach; ?>
    </div>
    <div class="container new_art" id="main_page_search_block" style="display:none;">
        
    </div>

    <div class="popular_block">
        <div class="container">
            <h2>Самое популярное</h2>
            <div class="row">
                <?php $effectOrder = array(0, 2, 2, 1);
                $i = 0; ?>
                <?php foreach ($this->postsBlock2 as $key => $value) : ?>
                    <div class="col-sm-6 col-md-3">
                        <div class="pop_art_block wow <?php echo $effectsArray[$effectOrder[$i]]; ?>">
                            <div class="pop_art_img">
                                <img src="public/image/statyi/<?php echo $value['img']; ?>" alt="<?php echo $value['name']; ?>">
                            </div>
                            <div class="pop_art_title">
                                <a href="<?php echo $this->baseUrl(); ?>/<?php echo($value['razdel_url']); ?>/<?php echo($value['href']); ?>/">
                                    <?php echo $value['name']; ?>
                                </a>
                            </div>
                        </div>
                    </div>
                    <?php $i++; ?>
                <?php endforeach; ?>
            </div>
        </div>		        
    </div>
</div>