<h2>Результаты поиска <span id="search-count"></span></h2>
<?php
$i = 0;
$effectsArray = array(
    0 => 'slideInLeft',
    1 => 'slideInRight',
    2 => 'zoomIn'
);
?>
<?php foreach ($this->searchresult as $key => $value) : ?>
    <?php if ($i == 0) : ?>
        <div class="row">
        <?php endif; ?>    
        <div class="col-sm-6 col-md-6">
            <div class="new_art_block">
                <div class="new_art_img">
                    <a href="<?php echo $this->baseUrl(); ?>/<?php echo($value['razdel_url']); ?>/<?php echo($value['href']); ?>/">   
                        <img src="<?php echo $this->baseUrl(); ?>/public/image/statyi/<?php echo $value['img']; ?>" alt="<?php echo $value['name']; ?>">
                    </a>
                    <div class="new_art_lbl"><?php echo $value['razdel']; ?></div>
                </div>
                <div class="new_art_title">
                    <a href="<?php echo $this->baseUrl(); ?>/<?php echo($value['razdel_url']); ?>/<?php echo($value['href']); ?>/">
                        <?php echo $value['name']; ?>
                    </a>
                </div>
                <div class="new_art_date"><?php echo date("Y.m.d", $value['time']); ?></div>
            </div>
        </div>
        <?php if ($i == 1) : ?>
        </div>
    <?php endif; ?>
    <?php
    if ($i == 1) {
        $i = 0;
    } else {
        $i++;
    }
    ?>

<?php endforeach; ?>