<?php if ($this->pageCount) { ?>
<div class="paginationControl">
<?php if (isset($this->previous)) { ?>
    <a href="<?= $this->url(array('controller' => 'index', 'page' => $this->previous),'paginator2', TRUE); ?>">&lt;</a> |
<?php } else { ?>
    <span class="disabled">&lt;</span> |
<?php }
    foreach ($this->pagesInRange as $page) {
        if ($page != $this->current) { ?>
    <a href="<?= $this->url(array('controller' => 'index' , 'page' => $page),'paginator2', TRUE); ?>"><?= $page; ?></a> |
<?php } else { ?>
<?= $page; ?> |
<?php }
}  if (isset($this->next)) { ?>
<a href="<?= $this->url(array('controller' => 'index' ,  'page' => $this->next),'paginator2', TRUE); ?>">
&gt;
</a>
<?php } else { ?>
<span class="disabled">&gt;</span>
<?php } ?>
</div>
<?php } ?>
