<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <?php
        $seo = $this->metaseo($_SERVER['REQUEST_URI']);
        if ($seo): ?>
            <meta name="robots" content="noindex, nofollow" />
        <?php endif; ?>
        <title><?php echo($this->title()); ?></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8;" /> 

        <meta name="description" content="<?php echo($this->description()); ?>" />
        <meta name="keywords" content="<?php echo($this->keywords()); ?>" />
        <meta name="yandex-verification" content="65113a889bd2529b" />
	    <meta name="p:domain_verify" content="0e453fea4bac19d92b21f4a333dd3bbe" />
        <meta property="og:locale" content="ru_RU" />
        <meta property="og:type" content="article" />
        <meta property="og:title" content="<?php echo($this->title()); ?>" />
        <meta property="og:description" content="<?php echo($this->description()); ?>" />
        <meta property="og:url" content="http://<?= $_SERVER['HTTP_HOST']; ?><?= $_SERVER['REQUEST_URI']; ?>" />
        <meta property="og:image" content="<?php echo ($this->postImage($_SERVER['REQUEST_URI'])); ?>" />
        <meta property="og:site_name" content="<?= $_SERVER['HTTP_HOST']; ?>" />
        <meta property="article:published_time" content="<?php echo($this->date()); ?>" />
        <meta property="article:author" content="Elena Yurchenko" />
        
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/default.css" type="text/css" media="screen, projection" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/styles.css" type="text/css" media="screen, projection" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/font-awesome.css" type="text/css" media="screen, projection" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/animate.css"> 
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/custom.css"> 
    	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/social-likes_flat.css"> 
    

        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"> 
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/js/fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/js/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" type="text/css" media="screen" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/js/fancybox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" type="text/css" media="screen" />
	
	   
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/jquery.js"></script>
        <script type="text/javascript" async src="//assets.pinterest.com/js/pinit.js"></script> 
        <script src="<?php echo $this->baseUrl(); ?>/public/js/wow.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/js/DoubleTapToGo.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/fancybox/source/helpers/jquery.fancybox-media.js?v=1.0.6"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/fancybox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/script.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/jssor.slider.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/detect.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/social-likes.min.js"></script>

    </head>
    <body>
    	<style id="custom-dynamic-styles"></style>
        <div id="overlay"><img src="<?php echo $this->baseUrl() . '/public/image/loading-red.gif'; ?>" alt="Loading..." /></div>
        <div class="wrap">
            <header>
                <div class="container"> 
                    <div class="row">
                        <div class="col-md-12">
                            <nav id="nav" class="mainmenu"  role="navigation">
                                <input type="checkbox" id="mmenu" hidden />
                                <label for="mmenu" class="admenu">
                                    <span class="opn">Меню</span><span class="close">Закрыть</span><i class="fa fa-bars"></i><i class="fa fa-times"></i>
                                </label>
                                <div class="mainnav">
                                    <?= $this->headerMenu(); ?>
                                </div>	
                            </nav>	
                        </div>
                    </div>
                    <?= $this->menuTagsAndSearchBlock(); ?>
                </div>
            </header>
            <?php echo $this->layout()->content; ?>

            <footer>
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 foot_menu">		
                            <ul>
                                <li>
                                    <a class="a-restrict-color" href="<?php echo $this->baseUrl(); ?>/lookbook/" title="LookBook">LookBook</a>
                                </li>
                                <li>
                                    <a class="a-restrict-color" href="<?php echo $this->baseUrl(); ?>/dress-kod/" title="Дресс–Код">Дресс–Код</a>
                                </li>
                                <li>
                                    <a class="a-restrict-color" href="<?php echo $this->baseUrl(); ?>/legkaya-odezhda/" title="Легкая одежда">Легкая одежда</a>
                                </li>
                                <li>
                                    <a class="a-restrict-color" href="<?php echo $this->baseUrl(); ?>/verhnyaya-odezhda/" title="Верхняя одежда">Верхняя одежда</a>
                                </li>
                                <li>
                                    <a class="a-restrict-color" href="<?php echo $this->baseUrl(); ?>/stil/" title="Стиль">Стиль</a>
                                </li>
                                <li>
                                    <a class="a-restrict-color" href="<?php echo $this->baseUrl(); ?>/vechernyaya-i-svadebnaya-moda/" title="Вечерняя и свадебная мода">Вечерняя и свадебная мода</a>
                                </li>
                                <li>
                                    <a class="a-restrict-color" href="<?php echo $this->baseUrl(); ?>/obuv-i-aksessuary/" title="Обувь и аксессуары">Обувь и аксессуары</a>
                                </li>
                            </ul>				
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 copyr">	
                            All rights reserved. Jenstvennayamoda 2017.
                        </div>
                        <div class="col-md-6 contact">	
                            jenstvenayamoda@gmail.com 
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <div id="scrollup"><img alt="Прокрутить вверх" src="<?php echo $this->baseUrl(); ?>/public/image/up2.png"></div>
        <script>
            (function ($) {
                $(document).ready(function () {
                    // dropdown
                    $('.parent > a').append('<i style="margin-left:5px;" class="fa fa-caret-down" ></i>');
                    $('#nav li:has(ul)').doubleTapToGo();
                    $('#nav li ul li:has(ul)').doubleTapToGo();
                });
            })(jQuery);
        </script>
        <script>
            new WOW().init();
        </script>
        <script type='text/javascript'>

            // Добавить в Избранное
            function add_favorite(a) {
                title = document.title;
                url = document.location;
                try {
                    // Internet Explorer
                    window.external.AddFavorite(url, title);
                }
                catch (e) {
                    try {
                        // Mozilla
                        window.sidebar.addPanel(title, url, "");
                    }
                    catch (e) {
                        // Opera
                        if (typeof (opera) == "object") {
                            a.rel = "sidebar";
                            a.title = title;
                            a.url = url;
                            return true;
                        }
                        else {
                            // Unknown
                            alert('Нажмите Ctrl-D чтобы добавить страницу в закладки');
                        }
                    }
                }
                return false;
            }
        </script>
        <!-- Код для google analitics-->
        <script type="text/javascript">
//            var _gaq = _gaq || [];
//            _gaq.push(['_setAccount', 'UA-38000144-1']);
//            _gaq.push(['_trackPageview']);
//
//            (function () {
//                var ga = document.createElement('script');
//                ga.type = 'text/javascript';
//                ga.async = true;
//                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
//                var s = document.getElementsByTagName('script')[0];
//                s.parentNode.insertBefore(ga, s);
//            })();
        </script>  
        <script type="text/javascript">
            //<![CDATA[
            function addLink() {
                var body_element = document.getElementsByTagName('body')[0];
                var selection = window.getSelection();

                var pagelink = "<p>&copy; Источник: <a rel='nofollow' href='" + document.location.href + "'>" + document.location.href + "</a></p>";

                var copytext = selection + pagelink;
                var newdiv = document.createElement('div');
                newdiv.style.position = 'absolute';
                newdiv.style.left = '-99999px';
                body_element.appendChild(newdiv);
                newdiv.innerHTML = copytext;
                selection.selectAllChildren(newdiv);
                window.setTimeout(function () {
                    body_element.removeChild(newdiv);
                }, 0);
            }
            document.oncopy = addLink;
            //]]>
        </script>
    </body>
</html>